kind: Template
apiVersion: v1
metadata:
  name: osd-monitor
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: osd-monitor-pcplogs
  spec:
   accessModes:
   - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      service: osd-monitor
    name: osd-monitor
  spec:
    replicas: 1
    selector:
      service: osd-monitor
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          service: osd-monitor
      spec:
        serviceAccountName: osd-monitor
        volumes:
          - name: pcp-logs
            persistentVolumeClaim:
              claimName: osd-monitor-pcplogs
          - name: pcp-prom-endpoints
            configMap:
              name: osd-monitor-prom-endpoints
        containers:
        - image: '${IMAGE_PCP_BAYESIAN_CENTRAL_LOGGER}:${IMAGE_TAG}'
          name: pcp-bayesian-central-logger
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          resources: 
            limits:
              cpu: 100m
              memory: 64000Mi
            requests:
              cpu: 10m
              memory: 5120Mi
          env:
            - name: ZABBIX_SERVER
              value: zabbix.devshift.net
            - name: VALGRIND
              value: ~
        - image: '${IMAGE_PCP_PROMETHEUS_IN}:${IMAGE_TAG}'
          name: pcp-prometheus-in
          volumeMounts:
            - name: pcp-prom-endpoints
              mountPath: /var/lib/pcp/pmdas/prometheus/urls.d
          env:
            - name: PCP_HOSTNAME
              value: osio
            - name: PMCD_PORT
              value: "54320"
          ports:
            - containerPort: 54320
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 1m
              memory: 128Mi
        - image: '${IMAGE_PCP_CENTRAL_WEBAPI}:${IMAGE_TAG}'
          name: pcp-central-webapi
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          ports:
            - containerPort: 44323
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 640Mi
            requests:
              cpu: 1m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /pmapi/1/metrics?target=kernel.all.load
              port: 44323
            initiaDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
        - image: '${IMAGE_PCP_BAYESIAN_WEBAPI_GUARD}:${IMAGE_TAG}'
          name: pcp-webapi-guard
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 1m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8000
            initiaDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    details:
      causes:
      - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: osd-monitor
    labels:
      service: osd-monitor
  spec:
    ports:
      - name: 'osd-monitor-webapi-guard'
        protocol: TCP
        port: 80
        targetPort: 8000
    selector:
      service: osd-monitor
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: osd-monitor
  spec:
    to:
      kind: Service
      name: osd-monitor
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: osd-monitor
parameters:
- name: IMAGE_PCP_BAYESIAN_CENTRAL_LOGGER
  value: quay.io/openshiftio/rhel-perf-pcp-bayesian-central-logger
- name: IMAGE_PCP_CENTRAL_WEBAPI
  value: quay.io/openshiftio/rhel-perf-pcp-central-webapi
- name: IMAGE_PCP_BAYESIAN_WEBAPI_GUARD
  value: quay.io/openshiftio/rhel-perf-pcp-bayesian-webapi-guard
- name: IMAGE_PCP_PROMETHEUS_IN
  value: quay.io/openshiftio/rhel-perf-pcp-prometheus-in
- name: IMAGE_TAG
  value: latest
