FROM registry.devshift.net/osio-prod/base/pcp:latest

# Expose pmwebd's main port on the host interface
EXPOSE 44323
ENV MALLOC_ARENA_MAX 1
ENTRYPOINT ["/usr/libexec/pcp/bin/pmwebd", "-v", "-v", "-h", "localhost", "-N"]
