FROM prod.registry.devshift.net/osio-prod/base/osd-loggers:latest

COPY fix-permissions /usr/bin/fix-permissions
COPY pmmgr+pmcd.sh   /pmmgr+pmcd.sh

COPY regen-tenant-list.sh /regen-tenant-list.sh

ADD pmmgr-tenants /etc/pcp/pmmgr-tenants

RUN chmod +x /usr/bin/fix-permissions && \
    /usr/bin/fix-permissions /regen-tenant-list.sh && \
    /usr/bin/fix-permissions /etc/pcp && \
    /usr/bin/fix-permissions /var/lib/pcp && \
    /usr/bin/fix-permissions /var/log/pcp

ENV MALLOC_ARENA_MAX 1
ENV ZABBIX_SERVER    localhost

ENV VALGRIND ""

# ENV VALGRIND /usr/bin/valgrind

VOLUME /var/log/pcp
ENTRYPOINT [ "/bin/sh", "/pmmgr+pmcd.sh" ]
