FROM prod.registry.devshift.net/osio-prod/base/httpd:latest

RUN sed -i -e "s,Listen 80,Listen 8001," /etc/httpd/conf/httpd.conf
RUN sed -i -e "s,logs/error_log,/dev/stderr," /etc/httpd/conf/httpd.conf
RUN sed -i -e "s,logs/access_log,/dev/stdout," /etc/httpd/conf/httpd.conf
EXPOSE 8001

COPY oso_central_webapi_guard.conf /etc/httpd/conf.d/oso_central_webapi_guard.conf
COPY pmwebd_guard.htpasswd /etc/httpd/conf/pmwebd_guard.htpasswd
RUN chmod a+rwX /run/httpd

VOLUME /var/log/pcp

STOPSIGNAL SIGWINCH

ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]
