FROM prod.registry.devshift.net/osio-prod/base/pcp:latest

# Expose pmwebd's main port on the host interface
EXPOSE 44323

VOLUME /var/log/pcp

ENV MALLOC_ARENA_MAX 1

# -M8?

ENTRYPOINT ["/usr/libexec/pcp/bin/pmwebd", "-v", "-v", "-G", "-X", "-R", "/usr/share/pcp/webapps", "-A", "/var/log/pcp/pmmgr", "-i", "15", "-P", "-J", "-L", "-M8"]
